// Code generated by entc, DO NOT EDIT.

package ent

import (
	"entgo/ent/schema"
	"entgo/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescAge is the schema descriptor for age field.
	userDescAge := userFields[0].Descriptor()
	// user.AgeValidator is a validator for the "age" field. It is called by the builders before save.
	user.AgeValidator = userDescAge.Validators[0].(func(int) error)
	// userDescName is the schema descriptor for Name field.
	userDescName := userFields[1].Descriptor()
	// user.DefaultName holds the default value on creation for the Name field.
	user.DefaultName = userDescName.Default.(string)
	// userDescPNumber is the schema descriptor for PNumber field.
	userDescPNumber := userFields[2].Descriptor()
	// user.DefaultPNumber holds the default value on creation for the PNumber field.
	user.DefaultPNumber = userDescPNumber.Default.(string)
}
